# Generated by Django 2.2 on 2009-12-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quant',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='items',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartlist'),
        ),
    ]
